spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    url: jdbc:h2:mem:customerServiceDB
  h2:
    console:
      enabled: true
      path: /h2-console
